### ISSUE TITLE
Any verdict from this experiment?

### ISSUE THREAD

**Issue by rclai** [brentvatne/fixed-height-windowed-list-view-experiment#5]
Was this a successful experiment?

**Comment by rgovindji** [comment]
I'm using this in [my app](http://trybunch.com), I also repackaged this module so it's easier to install https://github.com/rgovindji/react-native-atoz-list

@brentvatne If you want to merge the two projects let me know. It's mostly your code so if you want to take it over let me know.

**Comment by brentvatne** [comment]
@rgovindji - cool stuff! no need to merge them, you put in the effort to make it installable :+1:
